name: Storybook

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches: [ "master" ]
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Final
      run: |
        # Set the required variables
        repo_owner="yurasovm"
        repo_name="4p-uikit-storybook"
        event_type="trigger-workflow"

        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Authorization: Bearer ${{ secrets.PAT_4P }}" \
          https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
          -d "{\"event_type\": \"$event_type\" }"